name: Nix
permissions:
  contents: write
on:
  pull_request: null
  push:
    branches:
      - main
jobs:
  x86_64-linux---packages---sys-ide-bin:
    name: x86_64-linux---packages---sys-ide-bin
    runs-on:
      - ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-linux.sys-ide-bin --print-build-logs
  x86_64-linux---packages---sysml-v2-api-server:
    name: x86_64-linux---packages---sysml-v2-api-server
    runs-on:
      - ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-linux.sysml-v2-api-server --print-build-logs
  x86_64-linux---packages---sysml-v2-pilot-implementation:
    name: x86_64-linux---packages---sysml-v2-pilot-implementation
    runs-on:
      - ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-linux.sysml-v2-pilot-implementation --print-build-logs
  x86_64-linux---packages---syson-web:
    name: x86_64-linux---packages---syson-web
    runs-on:
      - ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-linux.syson-web --print-build-logs
  x86_64-linux---devShells---default:
    name: x86_64-linux---devShells---default
    runs-on:
      - ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#devShells.x86_64-linux.default --print-build-logs
  x86_64-linux---checks---nixpkgs-fmt:
    name: x86_64-linux---checks---nixpkgs-fmt
    runs-on:
      - ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#checks.x86_64-linux.nixpkgs-fmt --print-build-logs
  x86_64-linux---check:
    name: Check on x86_64-linux
    runs-on:
      - ubuntu-latest
    needs:
      - x86_64-linux---checks---nixpkgs-fmt
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Check
        run: nix flake check . --print-build-logs
  x86_64-darwin---packages---sys-ide-bin:
    name: x86_64-darwin---packages---sys-ide-bin
    runs-on:
      - macos-13
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-darwin.sys-ide-bin --print-build-logs
  x86_64-darwin---packages---sysml-v2-api-server:
    name: x86_64-darwin---packages---sysml-v2-api-server
    runs-on:
      - macos-13
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-darwin.sysml-v2-api-server --print-build-logs
  x86_64-darwin---packages---sysml-v2-pilot-implementation:
    name: x86_64-darwin---packages---sysml-v2-pilot-implementation
    runs-on:
      - macos-13
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-darwin.sysml-v2-pilot-implementation --print-build-logs
  x86_64-darwin---packages---syson-web:
    name: x86_64-darwin---packages---syson-web
    runs-on:
      - macos-13
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-darwin.syson-web --print-build-logs
  x86_64-darwin---devShells---default:
    name: x86_64-darwin---devShells---default
    runs-on:
      - macos-13
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#devShells.x86_64-darwin.default --print-build-logs
  x86_64-darwin---checks---nixpkgs-fmt:
    name: x86_64-darwin---checks---nixpkgs-fmt
    runs-on:
      - macos-13
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#checks.x86_64-darwin.nixpkgs-fmt --print-build-logs
  x86_64-darwin---check:
    name: Check on x86_64-darwin
    runs-on:
      - macos-13
    needs:
      - x86_64-darwin---checks---nixpkgs-fmt
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Check
        run: nix flake check . --print-build-logs
